"""initial_schema

Revision ID: be68d3d26ac1
Revises: 
Create Date: 2026-03-29 01:06:52.813380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be68d3d26ac1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('cardinality', sa.String(length=10), nullable=False),
    sa.Column('filterable', sa.Boolean(), nullable=False),
    sa.Column('sortable', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_dimensions_id'), 'taxonomy_dimensions', ['id'], unique=False)
    op.create_index(op.f('ix_taxonomy_dimensions_name'), 'taxonomy_dimensions', ['name'], unique=True)
    op.create_table('font_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'alias', name='uq_font_alias')
    )
    op.create_index(op.f('ix_font_aliases_alias'), 'font_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_font_aliases_id'), 'font_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_font_aliases_sample_id'), 'font_aliases', ['sample_id'], unique=False)
    op.create_table('font_search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('font_name', sa.String(length=255), nullable=True),
    sa.Column('font_category', sa.String(length=100), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('era', sa.String(length=100), nullable=True),
    sa.Column('origin_context', sa.String(length=100), nullable=True),
    sa.Column('restoration_status', sa.String(length=100), nullable=True),
    sa.Column('rights_status', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('glyph_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('moods', sa.Text(), nullable=True),
    sa.Column('use_cases', sa.Text(), nullable=True),
    sa.Column('visual_traits', sa.Text(), nullable=True),
    sa.Column('construction_traits', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('feature_vector', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_font_search_index_era'), 'font_search_index', ['era'], unique=False)
    op.create_index(op.f('ix_font_search_index_font_category'), 'font_search_index', ['font_category'], unique=False)
    op.create_index(op.f('ix_font_search_index_font_name'), 'font_search_index', ['font_name'], unique=False)
    op.create_index(op.f('ix_font_search_index_genre'), 'font_search_index', ['genre'], unique=False)
    op.create_index(op.f('ix_font_search_index_id'), 'font_search_index', ['id'], unique=False)
    op.create_index(op.f('ix_font_search_index_origin_context'), 'font_search_index', ['origin_context'], unique=False)
    op.create_index(op.f('ix_font_search_index_restoration_status'), 'font_search_index', ['restoration_status'], unique=False)
    op.create_index(op.f('ix_font_search_index_rights_status'), 'font_search_index', ['rights_status'], unique=False)
    op.create_index(op.f('ix_font_search_index_sample_id'), 'font_search_index', ['sample_id'], unique=True)
    op.create_index(op.f('ix_font_search_index_style'), 'font_search_index', ['style'], unique=False)
    op.create_table('font_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('width', sa.String(length=100), nullable=True),
    sa.Column('slope', sa.String(length=100), nullable=True),
    sa.Column('optical_size', sa.String(length=100), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'variant_name', name='uq_font_variant')
    )
    op.create_index(op.f('ix_font_variants_id'), 'font_variants', ['id'], unique=False)
    op.create_index(op.f('ix_font_variants_sample_id'), 'font_variants', ['sample_id'], unique=False)
    op.create_table('glyph_coverage_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('total_glyphs', sa.Integer(), nullable=False),
    sa.Column('verified_glyphs', sa.Integer(), nullable=False),
    sa.Column('latin_basic_count', sa.Integer(), nullable=False),
    sa.Column('latin_extended_count', sa.Integer(), nullable=False),
    sa.Column('digits_count', sa.Integer(), nullable=False),
    sa.Column('punctuation_count', sa.Integer(), nullable=False),
    sa.Column('coverage_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glyph_coverage_summaries_id'), 'glyph_coverage_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_glyph_coverage_summaries_sample_id'), 'glyph_coverage_summaries', ['sample_id'], unique=True)
    op.create_table('source_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('repository', sa.String(length=500), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('scan_filename', sa.String(length=255), nullable=True),
    sa.Column('scan_resolution_dpi', sa.Integer(), nullable=True),
    sa.Column('rights_statement', sa.Text(), nullable=True),
    sa.Column('rights_uri', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_artifacts_id'), 'source_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_source_artifacts_sample_id'), 'source_artifacts', ['sample_id'], unique=False)
    op.create_table('taxonomy_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['taxonomy_dimensions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_id', 'value', name='uq_taxonomy_term')
    )
    op.create_index(op.f('ix_taxonomy_terms_dimension_id'), 'taxonomy_terms', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_taxonomy_terms_id'), 'taxonomy_terms', ['id'], unique=False)
    op.create_index(op.f('ix_taxonomy_terms_value'), 'taxonomy_terms', ['value'], unique=False)
    op.create_table('font_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['font_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_font_files_id'), 'font_files', ['id'], unique=False)
    op.create_index(op.f('ix_font_files_sample_id'), 'font_files', ['sample_id'], unique=False)
    op.create_index(op.f('ix_font_files_variant_id'), 'font_files', ['variant_id'], unique=False)
    op.create_table('font_sample_taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['taxonomy_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'term_id', name='uq_sample_taxonomy')
    )
    op.create_index(op.f('ix_font_sample_taxonomy_id'), 'font_sample_taxonomy', ['id'], unique=False)
    op.create_index(op.f('ix_font_sample_taxonomy_sample_id'), 'font_sample_taxonomy', ['sample_id'], unique=False)
    op.create_index(op.f('ix_font_sample_taxonomy_term_id'), 'font_sample_taxonomy', ['term_id'], unique=False)
    op.create_index('ix_sample_taxonomy_sample', 'font_sample_taxonomy', ['sample_id'], unique=False)
    op.create_index('ix_sample_taxonomy_term', 'font_sample_taxonomy', ['term_id'], unique=False)
    op.create_table('preview_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['font_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preview_assets_id'), 'preview_assets', ['id'], unique=False)
    op.create_index(op.f('ix_preview_assets_sample_id'), 'preview_assets', ['sample_id'], unique=False)
    op.create_index(op.f('ix_preview_assets_variant_id'), 'preview_assets', ['variant_id'], unique=False)
    op.create_table('provenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['source_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sample_id'], ['font_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_records_artifact_id'), 'provenance_records', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_provenance_records_id'), 'provenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_provenance_records_sample_id'), 'provenance_records', ['sample_id'], unique=False)
    op.create_index('ix_provenance_sample_event', 'provenance_records', ['sample_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provenance_sample_event', table_name='provenance_records')
    op.drop_index(op.f('ix_provenance_records_sample_id'), table_name='provenance_records')
    op.drop_index(op.f('ix_provenance_records_id'), table_name='provenance_records')
    op.drop_index(op.f('ix_provenance_records_artifact_id'), table_name='provenance_records')
    op.drop_table('provenance_records')
    op.drop_index(op.f('ix_preview_assets_variant_id'), table_name='preview_assets')
    op.drop_index(op.f('ix_preview_assets_sample_id'), table_name='preview_assets')
    op.drop_index(op.f('ix_preview_assets_id'), table_name='preview_assets')
    op.drop_table('preview_assets')
    op.drop_index('ix_sample_taxonomy_term', table_name='font_sample_taxonomy')
    op.drop_index('ix_sample_taxonomy_sample', table_name='font_sample_taxonomy')
    op.drop_index(op.f('ix_font_sample_taxonomy_term_id'), table_name='font_sample_taxonomy')
    op.drop_index(op.f('ix_font_sample_taxonomy_sample_id'), table_name='font_sample_taxonomy')
    op.drop_index(op.f('ix_font_sample_taxonomy_id'), table_name='font_sample_taxonomy')
    op.drop_table('font_sample_taxonomy')
    op.drop_index(op.f('ix_font_files_variant_id'), table_name='font_files')
    op.drop_index(op.f('ix_font_files_sample_id'), table_name='font_files')
    op.drop_index(op.f('ix_font_files_id'), table_name='font_files')
    op.drop_table('font_files')
    op.drop_index(op.f('ix_taxonomy_terms_value'), table_name='taxonomy_terms')
    op.drop_index(op.f('ix_taxonomy_terms_id'), table_name='taxonomy_terms')
    op.drop_index(op.f('ix_taxonomy_terms_dimension_id'), table_name='taxonomy_terms')
    op.drop_table('taxonomy_terms')
    op.drop_index(op.f('ix_source_artifacts_sample_id'), table_name='source_artifacts')
    op.drop_index(op.f('ix_source_artifacts_id'), table_name='source_artifacts')
    op.drop_table('source_artifacts')
    op.drop_index(op.f('ix_glyph_coverage_summaries_sample_id'), table_name='glyph_coverage_summaries')
    op.drop_index(op.f('ix_glyph_coverage_summaries_id'), table_name='glyph_coverage_summaries')
    op.drop_table('glyph_coverage_summaries')
    op.drop_index(op.f('ix_font_variants_sample_id'), table_name='font_variants')
    op.drop_index(op.f('ix_font_variants_id'), table_name='font_variants')
    op.drop_table('font_variants')
    op.drop_index(op.f('ix_font_search_index_style'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_sample_id'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_rights_status'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_restoration_status'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_origin_context'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_id'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_genre'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_font_name'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_font_category'), table_name='font_search_index')
    op.drop_index(op.f('ix_font_search_index_era'), table_name='font_search_index')
    op.drop_table('font_search_index')
    op.drop_index(op.f('ix_font_aliases_sample_id'), table_name='font_aliases')
    op.drop_index(op.f('ix_font_aliases_id'), table_name='font_aliases')
    op.drop_index(op.f('ix_font_aliases_alias'), table_name='font_aliases')
    op.drop_table('font_aliases')
    op.drop_index(op.f('ix_taxonomy_dimensions_name'), table_name='taxonomy_dimensions')
    op.drop_index(op.f('ix_taxonomy_dimensions_id'), table_name='taxonomy_dimensions')
    op.drop_table('taxonomy_dimensions')
    # ### end Alembic commands ###
